'use strict';

/**
 * Converts a BUILT Docusaurus page into the Markdown twin served beside it.
 *
 * ---------------------------------------------------------------------------
 * WHY A SECOND CONVERTER, AND WHY IT DOES NOT REPLACE THE FIRST
 * ---------------------------------------------------------------------------
 *
 * `lib/mdx-to-md.js` (`cleanMdx`) is the converter for this project's Markdown.
 * It knows our frontmatter, our `<Tabs>`/`<TabItem>`, our `<DocCardList>`, our
 * admonitions and our link rewriting, and `plugins/markdown-twins.js` runs it
 * for every route that has a source file. It stays exactly as it is, and every
 * route it already covers is still converted by it, from the same candidate in
 * the same order, to the same bytes. This module is not on that path and must
 * never be put on it.
 *
 * It exists for the routes that have NO source file to convert. Measured on the
 * build of 2026-08-30, ten of 271 routes:
 *
 *     /docs/                              src/pages/index.tsx, a React page
 *     /docs/404.html                      the theme's NotFound page
 *     /docs/search/                       @docusaurus/theme-search-algolia
 *     /docs/api/tags/     + 3 tag pages   generated by plugin-content-docs
 *     /docs/sheets/tags/  + 2 tag pages   generated by plugin-content-docs
 *
 * For these there is no `.md`, `.mdx`, `/index.md` or `/index.mdx` anywhere in
 * the tree. `cleanMdx` is not the wrong tool for them; it has no input at all.
 * The rendered page is the only statement of what these routes say, so it is
 * what the twin is derived from.
 *
 * ---------------------------------------------------------------------------
 * WHY IT MATTERS THAT THEY EXIST AT ALL
 * ---------------------------------------------------------------------------
 *
 * `marketdata-docusaurus-proxy` -- the worker fronting `/docs/*` -- answers
 * `Accept: text/markdown` today, and a route with no twin FALLS THROUGH to the
 * HTML proxy. So a reader asking `/docs/` for Markdown gets `text/html`: not
 * what was asked for, but a page.
 *
 * That worker is being retired (MarketData-App/www-marketdata-app#15) and its
 * negotiation replaced by a Cloudflare Transform Rule, which rewrites the path
 * to `<path>index.md` unconditionally. A rewrite cannot fall through. So on the
 * day the worker is switched off, every route without a twin turns from HTML
 * into a 404, with no deploy and no other cause. The exclusion is invisible
 * from outside until then, which is why `postBuild` now fails the build rather
 * than counting them.
 *
 * ---------------------------------------------------------------------------
 * WHY TURNDOWN, AND WHY THIS CONFIGURATION
 * ---------------------------------------------------------------------------
 *
 * `MarketDataApp/website` -- the other source merged into this origin, at `/` --
 * already derives all of ITS twins from rendered HTML, in
 * `src/integrations/markdown-versions.mjs`, using Turndown over `@mixmark-io/domino`.
 * The options, the table rule and the image rule below are that file's, on
 * purpose: the two halves of one origin should not answer the same question in
 * two Markdown dialects. That repo is private with no `exports`, so it cannot
 * be imported; this is the same vendoring the worker did with `mdx-to-md.js`.
 *
 * Where it deliberately DIVERGES from that file:
 *
 *   - No `twinHeader`. Twins under `/docs/` are the converted body and nothing
 *     else, because that is the shape `cleanMdx` has always produced and the
 *     shape the worker has always served. One shape per origin half beats
 *     matching the other half and splitting this one.
 *   - `[data-pagefind-ignore]` is not in STRIP_SELECTORS. Pagefind is Astro-side;
 *     no component here carries the attribute, and a selector that can never
 *     match reads like a guarantee it is not making.
 */

const TurndownService = require('turndown');
const domino = require('@mixmark-io/domino');

/**
 * Chrome inside the content root that is navigation, decoration or script
 * rather than substance.
 *
 * `form` costs the search page its search box, which leaves `/docs/search/`
 * as its heading alone. That is correct: the box is an input, and an input is
 * not something a Markdown reader can use. The route still answers 200, which
 * is the property the Transform Rule needs.
 *
 * `.hash-link` is the zero-width anchor Docusaurus hangs off every heading. It
 * renders as `[​](#A)` -- a link whose label is U+200B -- once per heading.
 */
const STRIP_SELECTORS = [
  'script',
  'style',
  'noscript',
  'svg',
  'iframe',
  'form',
  'nav',
  '.hash-link',
  '.theme-doc-sidebar-container',
  '.theme-doc-toc-desktop',
  '.theme-doc-toc-mobile',
  '.theme-doc-breadcrumbs',
  '.pagination-nav',
  "[aria-hidden='true']",
];

function decodeEntities(s) {
  return String(s)
    .replace(/&#(\d+);/g, (_, n) => String.fromCharCode(Number(n)))
    .replace(/&#x([0-9a-f]+);/gi, (_, n) => String.fromCharCode(parseInt(n, 16)))
    .replace(/&quot;/g, '"')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&amp;/g, '&');
}

function makeTurndown() {
  const td = new TurndownService({
    headingStyle: 'atx',
    codeBlockStyle: 'fenced',
    bulletListMarker: '-',
  });

  // Turndown ships no table rule, so a table collapses into an unlabelled run
  // of cell text ("A B 1 2"). Nothing on the ten routes this module covers has
  // a table today; it is here because the set is defined by "has no source",
  // and the next page to land in it is not chosen by us.
  td.addRule('table', {
    filter: 'table',
    replacement: (_content, node) => {
      const rows = Array.from(node.querySelectorAll('tr'));
      if (!rows.length) return '';

      // innerHTML with tags replaced by a space, not textContent: textContent
      // runs adjacent elements together, so a label with a tooltip <span>
      // beside it comes out as one word.
      const text = (el) =>
        decodeEntities(String(el.innerHTML || '').replace(/<[^>]+>/g, ' '))
          .replace(/\s+/g, ' ')
          .trim()
          .replace(/\|/g, '\\|');

      // Expand colspan so every row lands on the same grid. A header narrower
      // than the body is malformed GFM and parsers silently drop the extra
      // columns.
      const grid = rows.map((tr) =>
        Array.from(tr.children).flatMap((c) => {
          const span = Math.max(1, parseInt(c.getAttribute('colspan') || '1', 10) || 1);
          return [text(c), ...Array(span - 1).fill('')];
        })
      );

      const width = Math.max(...grid.map((r) => r.length));
      if (!width) return '';
      const pad = (r) => [...r, ...Array(width - r.length).fill('')];
      const line = (r) => `| ${pad(r).join(' | ')} |`;

      return [
        '',
        line(grid[0]),
        `| ${Array(width).fill('---').join(' | ')} |`,
        ...grid.slice(1).map(line),
        '',
      ].join('\n');
    },
  });

  // An image contributes its alt text at most. The docs root ships two <img>
  // per feature card -- one light, one dark, same alt -- and one of them is a
  // base64 data URI, so emitting the src would put the binary in the twin.
  td.addRule('image', {
    filter: 'img',
    replacement: (_c, node) => {
      const alt = (node.getAttribute('alt') || '').trim();
      return alt ? `(image: ${alt})` : '';
    },
  });

  return td;
}

let turndown = null;

/**
 * The element the twin is derived from.
 *
 * `.main-wrapper` and NOT `<main>`, which is the one place this diverges from
 * the sibling implementation, because Docusaurus puts things outside `<main>`
 * that the page is about. On the docs root, `src/pages/index.tsx` renders
 * `<HomepageHeader />` as a SIBLING of `<main>`, so `<main>` alone is three
 * feature cards with no `<h1>`, no tagline and no "Get Started" link.
 * `/docs/search/` has no `<main>` element at all.
 *
 * Both are inside `.main-wrapper`, and the navbar and the footer are outside
 * it, so it is the selector that means "this page" on every route here.
 */
function contentRoot(doc) {
  return doc.querySelector('.main-wrapper') || doc.querySelector('main') || null;
}

/**
 * Four repairs to the rendered tree that Turndown cannot make for itself,
 * because each needs to see more of the DOM than one node's replacement does.
 * All four were observed in the first build that emitted these ten twins.
 *
 * 1. A LINK WRAPPING A HEADING. Both the docs root's feature cards and every
 *    tag page's result list are `<a href><h3>Title</h3><p>Blurb</p></a>`.
 *    Turndown emits that literally -- `[` , a blank line, `### Title`, a blank
 *    line, `](url)` -- which is a broken link and a heading that is not one.
 *    The anchor is unwrapped and the link moved INSIDE the heading, so the
 *    blurb and the images stay where they are and `### [Title](url)` is a real
 *    heading and a real link.
 *
 * 2. A LINK WITH NOTHING LEFT IN IT. `/docs/search/` links the Algolia logo,
 *    which is an `<svg>`, which STRIP_SELECTORS removes -- leaving `[](url)`.
 *    An anchor with no text and no captioned image is dropped.
 *
 * 3. A TAG'S COUNT RUNNING INTO ITS NAME. Docusaurus writes a tag link as
 *    `<a>API: Beta<span>1</span></a>`, so the twin said `API: Beta1` and named
 *    a tag that does not exist. The count is parenthesised.
 *
 * 4. THE SAME IMAGE TWICE. Docusaurus's themed images render a light and a
 *    dark `<img>` with identical alt text, so each feature card said
 *    `(image: Market Data API)(image: Market Data API)`. One is dropped.
 */
function normalise(root, doc) {
  // 4, before 1: the pair are siblings, and unwrapping an anchor moves them.
  for (const img of Array.from(root.querySelectorAll('img'))) {
    const prev = img.previousElementSibling;
    const alt = (img.getAttribute('alt') || '').trim();
    if (prev && prev.tagName === 'IMG' && alt && (prev.getAttribute('alt') || '').trim() === alt) {
      img.parentNode?.removeChild(img);
    }
  }

  // 3, before 1: the count lives in an anchor that 1 may replace.
  for (const span of Array.from(root.querySelectorAll('a[class*="tagWithCount"] > span'))) {
    const n = (span.textContent || '').trim();
    if (n) span.textContent = ` (${n})`;
  }

  // 1.
  for (const a of Array.from(root.querySelectorAll('a[href]'))) {
    const heading = a.querySelector('h1, h2, h3, h4, h5, h6');
    if (!heading || !a.parentNode) continue;

    const link = doc.createElement('a');
    link.setAttribute('href', a.getAttribute('href'));
    while (heading.firstChild) link.appendChild(heading.firstChild);
    heading.appendChild(link);

    const parent = a.parentNode;
    while (a.firstChild) parent.insertBefore(a.firstChild, a);
    parent.removeChild(a);
  }

  // 2, last: 1 and 4 are what empty an anchor out.
  for (const a of Array.from(root.querySelectorAll('a[href]'))) {
    if ((a.textContent || '').trim()) continue;
    const captioned = Array.from(a.querySelectorAll('img')).some(
      (img) => (img.getAttribute('alt') || '').trim()
    );
    if (!captioned) a.parentNode?.removeChild(a);
  }
}

/**
 * `<title>` with the site name taken off: "Tags | Market Data Docs (staging)"
 * -> "Tags". The suffix is `siteConfig.title`, which differs between staging
 * and production, so it is passed in rather than matched by pattern.
 */
function pageTitle(doc, siteTitle) {
  const raw = decodeEntities(doc.querySelector('title')?.textContent ?? '').trim();
  if (!raw || !siteTitle) return raw;
  const suffix = ` | ${siteTitle}`;
  return raw.endsWith(suffix) ? raw.slice(0, -suffix.length).trim() : raw;
}

/**
 * Rewrites root-relative hrefs to absolute, so a twin read on its own resolves
 * its links. Built hrefs already carry the `/docs/` prefix, so `origin` is the
 * bare origin and the result matches what `cleanMdx` produces for a source
 * route: `https://www.marketdata.app/docs/...`.
 */
function absolutiseLinks(root, origin) {
  if (!origin) return;
  for (const a of Array.from(root.querySelectorAll('a[href]'))) {
    const href = a.getAttribute('href');
    if (href && href.startsWith('/') && !href.startsWith('//')) {
      a.setAttribute('href', origin + href);
    }
  }
}

const tidy = (md) =>
  md
    .replace(/​/g, '')
    .replace(/\n{3,}/g, '\n\n')
    .replace(/[ \t]+$/gm, '')
    .trim();

/**
 * @param {string} html       A built page's full HTML.
 * @param {object} [opts]
 * @param {string} [opts.origin]     Bare origin for absolutising links.
 * @param {string} [opts.siteTitle]  `siteConfig.title`, stripped off `<title>`.
 * @returns {string|null}  The Markdown, or null when the page has no content
 *                         root -- which the caller must treat as a failure,
 *                         not as a route to skip.
 */
function cleanHtml(html, opts = {}) {
  const origin = opts.origin ?? '';
  const siteTitle = opts.siteTitle ?? '';

  const doc = domino.createWindow(String(html)).document;
  const root = contentRoot(doc);
  if (!root) return null;

  for (const sel of STRIP_SELECTORS) {
    for (const node of Array.from(root.querySelectorAll(sel))) {
      node.parentNode?.removeChild(node);
    }
  }
  normalise(root, doc);
  absolutiseLinks(root, origin);

  turndown = turndown || makeTurndown();
  const body = tidy(turndown.turndown(root));

  // Only when the page rendered no <h1>. Every route this covers today has
  // one inside .main-wrapper, so this is a guard for the next one rather than
  // a step in the common path.
  const title = pageTitle(doc, siteTitle);
  const titled = /^#\s/.test(body) || !title ? body : `# ${title}\n\n${body}`;

  return titled.replace(/\s+$/, '') + '\n';
}

module.exports = { cleanHtml, STRIP_SELECTORS };
