/**
 * Integration test: fetches the live sitemap and verifies every doc URL
 * returns valid markdown via Accept: text/markdown header.
 *
 * Run with: yarn test:integration
 * Requires network access to www.marketdata.app
 */
import { describe, it, expect } from 'vitest';

const SITEMAP_URL = 'https://www.marketdata.app/docs/sitemap.xml';

// Pages generated by Docusaurus that have no markdown source
const SKIP_PATTERNS = [
  '/docs/search',
  '/docs/docs/',        // root landing page (auto-generated)
  '/tags',              // tag listing pages
];

// Pages with no markdown source — auto-generated or mapped to unexpected paths
// See: https://github.com/MarketDataApp/documentation/issues/127
const SKIP_EXACT = [
  '/docs/',             // root page source is at docs/index.md, outside doc plugin paths
  '/docs/sdk/stocks',   // broken category URLs (should be /sdk/go/stocks, etc.)
  '/docs/sdk/markets',
  '/docs/sdk/options',
];

function shouldSkip(url) {
  const path = new URL(url).pathname;
  if (SKIP_EXACT.includes(path)) return true;
  return SKIP_PATTERNS.some((pattern) => url.includes(pattern));
}

async function fetchSitemapUrls() {
  const res = await fetch(SITEMAP_URL);
  const xml = await res.text();
  const urls = [];
  for (const match of xml.matchAll(/<loc>([^<]+)<\/loc>/g)) {
    urls.push(match[1]);
  }
  return urls;
}

describe('markdown serving (live sitemap)', async () => {
  const allUrls = await fetchSitemapUrls();
  const docUrls = allUrls.filter((url) => !shouldSkip(url));

  it(`sitemap has URLs to test`, () => {
    expect(docUrls.length).toBeGreaterThan(50);
  });

  for (const url of docUrls) {
    const path = new URL(url).pathname;

    it(`${path} returns markdown`, async () => {
      const res = await fetch(url, {
        headers: { Accept: 'text/markdown' },
        redirect: 'follow',
      });

      expect(res.status, `${path} returned ${res.status}`).toBe(200);
      expect(res.headers.get('content-type')).toContain('text/markdown');

      const text = await res.text();
      expect(text.length, `${path} returned empty body`).toBeGreaterThan(0);

      // Should not contain raw frontmatter
      expect(text.startsWith('---\n'), `${path} still has frontmatter`).toBe(false);

      // Should not contain MDX import statements
      expect(text, `${path} still has import statements`).not.toMatch(/^import\s+\w+\s+from\s+"/m);

      // Should not contain raw JSX tags from Docusaurus components
      expect(text, `${path} still has <Tabs>`).not.toContain('<Tabs>');
      expect(text, `${path} still has <TabItem`).not.toMatch(/<TabItem\s/);
    });
  }
});
